free-proxy-list:
  dir: /app/resources/free-proxy-list
  socks5-dir: ${free-proxy-list.dir}/proxies/protocols/socks5/data.json
  socks4-dir: ${free-proxy-list.dir}/proxies/protocols/socks4/data.json
  git-url: https://github.com/proxifly/free-proxy-list

geonode:
  api:
    root-url: https://proxylist.geonode.com
    proxy-list: ${geonode.api.root-url}/api/proxy-list?limit={limit}&page={page}&sort_by={sortBy}&sort_type={sortType}

proxyscrape:
  api:
    root-url: https://api.proxyscrape.com/
    proxy-list: ${proxyscrape.api.root-url}/v3/free-proxy-list/get?request=displayproxies&proxy_format=protocolipport&format=json&timeout=20000&limit=100&ssl=yes

urls-to-check-ip: https://teamo.ru,https://teamo.ru

spring:
  application:
    name: proxy-provider
  main:
    web-application-type: none
  rabbitmq:
    username: proxy_provider_app
    password: L~mBMqa)/{9:J4wFpG6z,C
    host: rabbit-mq
    port: 5672
    producer:
      proxy-pub:
        exc: proxy-exc
        route-key: proxy.dto

logging:
  config: /app/resources/logback-spring.xml

logback:
  destination:
    url: logstash
    port: 5000