services:
  opensearch:
    image: opensearchproject/opensearch:2.15.0
    container_name: opensearch-local
    environment:
      - TZ=Europe/Moscow
      - node.name=opensearch
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Elk_admin123
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - "discovery.type=single-node"
    networks:
      - internal_net
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u admin:Elk_admin123 --silent --fail https://localhost:9200/_cluster/health || exit 1"]
      interval: 60s
      timeout: 60s
      retries: 5

  dashboard:
    restart: always
    image: opensearchproject/opensearch-dashboards:2.15.0
    container_name: dashboard-local
    environment:
      TZ: Europe/Moscow
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      DISABLE_INSTALL_DEMO_CONFIG: "true"
    ports:
      - 5601:5601
    networks:
      - internal_net
    depends_on:
      opensearch:
         condition: service_healthy

  logstash:
    container_name: logstash-local
    build:
      context: ./logstash
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Moscow
    ports:
      - 5000:5000
    networks:
      - internal_net
    depends_on:
      opensearch:
         condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "bin/logstash -t"]
      interval: 90s
      timeout: 60s
      retries: 5

  rabbit-mq:
    container_name: rabbit-mq-local
    environment:
      - TZ=Europe/Moscow
    command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    networks:
      - internal_net
    ports:
      - '15672:15672'
      - '5672:5672'
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  database:
    container_name: database-local
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    networks:
      - internal_net
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d teamo_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s


networks:
  internal_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
