api:
  personotexistimg: https://thispersondoesnotexist.com/
  unsplash:
    search-url: https://api.unsplash.com/search/photos
    random-url: https://api.unsplash.com/photos/random
    access-key: 8A_9v-sMYvUJWxGMo7iehQbCKXQlMqZ8X1ClgIzdlqc
    secret-key: KDuvQgNJoCN-PqIg8feEvMBDbljzVg2NGaX3MunHEUk
  pexels:
    search-url: https://api.pexels.com/v1/search
    access-key: WIcfbU65AcOO96hi7hY5qbmpFGOEx0MaEawmkUqUpXhzyv1pTJitXS2g
  pixabay:
    search-url: https://pixabay.com/api/
    access-key: 45793961-b754e262a06e937f9d5242608

inner-api:
  CCS:
    check: http://localhost:8080/register/check/reg/status
    reg: http://localhost:8080/register/reg/object

images:
  count: 15
  dir: ./images
  temp-dir: ./images/temp

spring:
  application:
    name: img-generator
  web:
    resources:
      static-locations: file:/app/resources/static/
  thymeleaf:
    check-template: true
    check-template-location: true
    prefix: file:/app/resources/templates/
  rabbitmq:
    username: img_generator_app
    password: TyQlBQ.315;%O%
    host: rabbit-mq
    port: 5672
    pub:
      css:
        route-key: file.img.ava
        exc: img-ava-exc

logging:
  config: /app/resources/logback-spring.xml

logback:
  destination:
    url: logstash
    port: 5000