teamoAPI:
  baseUrl: https://api.teamo.ru

  nextStep: ${teamoAPI.baseUrl}/teamo.getNextStep
  cancelPsychoTesting: ${teamoAPI.baseUrl}/rtest.cancelPsychoTesting
  editMainInfo: ${teamoAPI.baseUrl}/user.editMainInfo
  skipConfirmation: ${teamoAPI.baseUrl}/phone.skipConfirmation

content-storage-serviceAPI:
  baseUrl: http://content-storage-service:8080/image-avatar

  countByGender: ${content-storage-serviceAPI.baseUrl}/get/count/by-gender
  infoBase64ByGender: ${content-storage-serviceAPI.baseUrl}/get/info-base64-struct/by-gender

web-driver:
  type: remote
  remote-url: http://chrome-stadalone:4444
  selenium-dir: /app/resources/selenium

file:
  photos:
    dir: /app/temp/photos

spring:
  application:
    name: teamo-auto-reg
  rabbitmq:
    username: teamo_auto_reg_app
    password: r2$L%)`C=;pJUPg]dm:VDu
    host: rabbit-mq
    port: 5672
    consumer:
      red-queen:
        que: reg-user-teamo-que
      proxy-provider:
        que: teamo-auto-reg-proxy-que
    producer:
      red-queen:
        exc: user-teamo-exc
        route-key: user.teamo.dto

logging:
  config: /app/resources/logback-spring.xml

logback:
  destination:
    url: logstash
    port: 5000